### ISSUE TITLE
error in windows 10

### ISSUE THREAD

**Issue by novia713** [CodingFree/Windows-Defender#1]
## i got this error executing -optimize in windows 10

timizing Windows Defender...
Set-MpPreference : Se produjo el siguiente error en la operación: 0x57
En C:\Users\Usuario\defender.ps1: 46 Carácter: 3
-   Set-MpPreference -ThreatIDDefaultAction_Actions 2 # Quarantine by d ...
-   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (MSFT_MpPreference:root\Microsoft...FT_MpPreference) [Set-MpPreference
    ], CimException
  - FullyQualifiedErrorId : HRESULT 0x57,Set-MpPreference

Set-MpPreference : No se encuentra ningún parámetro de posición que acepte el argumento '--ScanOnlyIfIdleEnabled'.
En C:\Users\Usuario\defender.ps1: 49 Carácter: 3
-   Set-MpPreference --ScanOnlyIfIdleEnabled $true # If CPU is idle, ru ...
-   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (:) [Set-MpPreference], ParameterBindingException
  - FullyQualifiedErrorId : PositionalParameterNotFound,Set-MpPreference

**Comment by CodingFree** [comment]
Set-MpPreference -ThreatIDDefaultAction_Actions is not working properly.
